### ISSUE TITLE
initial release

### ISSUE THREAD

**Issue by rfrohl** [Cropi/usbguard-notifier#24]
Hi, 
I wanted to ask if/when there will be an initial release. I package usbguard for openSUSE and would like to package a replacement for the usbguard-applet-qt. An official release would make packaging easier for me, as well as reporting bugs.

Thanks!

**Comment by Cropi** [comment]
Hi,

Thanks for reaching out to us. An initial release will be available as soon as the project is ready for that. We are currently working on fixing some bugs. It might take a few weeks.

Thanks for your patient!

**Comment by rfrohl** [comment]
@Cropi I thought I would follow up on this again, to get an idea how things are. Do you have an estimate when the notifier might be ready for an initial release ? Even a rough estimate would be helpful.

**Comment by Cropi** [comment]
Thank you for your patience @rfrohl .

[Initial pre-release 0.0.1](https://github.com/Cropi/usbguard-notifier/releases/tag/0.0.1)
