### ISSUE TITLE
notifier crash

### ISSUE THREAD

**Issue by radosroka** [Cropi/usbguard-notifier#54]
I'm running ```usbguard-daemon -d -k -c /etc/usbguard/usbguard-daemon.conf``` with notifier in the background and when I send a sigterm to usbguard-daemon, notifier crashes.

```
Nov 12 09:40:37 Axis systemd[1384]: usbguard_notifier.service: Main process exited, code=killed, status=11/SEGV
Nov 12 09:40:37 Axis systemd[1384]: usbguard_notifier.service: Failed with result 'signal'.
Nov 12 09:40:37 Axis systemd-coredump[28466]: Process 28433 (usbguard_notifi) of user 1000 dumped core.
                                              
                                              Stack trace of thread 28435:
                                              #0  0x0000000000406c88 n/a (/home/rsroka/sbin/usbguard_notifier)

```

**Comment by Cropi** [comment]
@tammar96 Take a look at it, thanks.

**Comment by Cropi** [comment]
I noticed from this:
```   #0  0x0000000000406c88 n/a (/home/rsroka/sbin/usbguard_notifier)```
that you are **not** using the right binary.

I would recommend you to reinstall usbguard-notifier along with the services file. It should solve the problem.
