### ISSUE TITLE
How do I allow the device?

### ISSUE THREAD

**Issue by frankenstein91** [Cropi/usbguard-notifier#55]
Hello,

I just installed this software on ArchLinux. I used to use the old QT program.
I have installed the program so far that I get a message when I connect a device via USB.
![grafik](https://user-images.githubusercontent.com/2527348/70389784-66f77800-19c4-11ea-8e3f-d0f782e0b841.png)
But unfortunately I can't find a way to create rules via GUI.

OS: Arch Linux x86_64
Kernel: 5.4.2-arch1-1
Shell: /bin/zsh 5.7.1
Resolution: 3840x1080 @ 59.97Hz
DE: Cinnamon 4.4.3
WM: Mutter (Muffin)
Terminal: terminology
CPU: Intel i7-8550U (8) @ 4.000GHz [50.0°on]
GPU: Intel UHD Graphics 620
Memory: 2960MiB / 31997MiB (9%)
GPU Driver: i915

**Comment by Cropi** [comment]
Hello @frankenstein91 ,

The purpose of this project is to detect [usbguard](https://github.com/USBGuard/usbguard/) policy modifications and device presence changes.
Unfortunately, you are not able to create rules via this GUI. Currently, the only solution is to use the usbguard CLI. Please note that the USBGuard QT program is going to be available in the near future.

**Comment by frankenstein91** [comment]
okay I hope to see it soon :)
currently I'm okay with the CLI... but I do not understand how to make rules for a long time

**Comment by Cropi** [comment]
If you are having problems with creating rules then you should take a look at https://usbguard.github.io/documentation/rule-language.html .
