### ISSUE TITLE
Full list of dependencies missing from the Readme

### ISSUE THREAD

**Issue by kisst** [Cropi/usbguard-notifier#56]
To be able to install, you need all kind of packages:
 - librsvg2-dev
 - libqb-dev
 - libnotify-dev
 etc

**Comment by Cropi** [comment]
Hello,

I did not include libqb-dev in the documentation, because it is provided by usbguard-dev.
However, in case of libnotify-dev and librsvg2-dev you are right.

Thanks for the feedback.
