### ISSUE TITLE
usbguard-notifier-cli does not actually do anything(?)

### ISSUE THREAD

**Issue by lemmy04** [Cropi/usbguard-notifier#60]
I just plugged in a thumbdrive, and I got the popup on my desktop, but:

`mathias@kirika:~> usbguard-notifier-cli
No notifications to show.`

Any ideas?

**Comment by Cropi** [comment]
Hi @lemmy04,

Sorry for the late reply. The idea behind usbguard-notifier-cli was to change the policy of a device according to the notifications. The most common use case would be to allow a device that you just plugged in to your machine by pressing a keyboard shortcut.  
This would make usbguard more user friendly , so you did not have to:

1. List devices using usbguard list-command
2. Select the appropriate device
3. Change the policy of the selected device by using usbguard allow|block|reject-device commands

Unfortunately, it has not been implemented.

**Comment by Cropi** [comment]
See https://github.com/Cropi/usbguard-notifier/issues/70 .
