### ISSUE TITLE
Crash after usb disconnect

### ISSUE THREAD

**Issue by monolidth** [Cropi/usbguard-notifier#64]
Hey Cropi,

I'm using the latest usbguard and usbguard-notifier version. I installed all required packages mentioned in the **README.md**.

I did following steps:
* ` ./autogen.sh`
* ` ./configure --prefix /home/$(id -un)`
*  `make`
*  `make install SYSTEMD_UNIT_DIR=/home/$(id -un)/.config/systemd/user/`
*  `systemctl enable --now --user usbguard-notifier.service`

### Trace
```
Connection has been established
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to show notification
[2]    40050 abort      sudo ./usbguard-notifier
```

If I run this using the debug flag. I receive this message
```
LOG: src/Notifier.cpp::102 [DevicePresenceChanged] Device presence changed signal
Connection has been established
```

I hope I could resolve this issue. Thanks for your help.

Regards,
William

**Comment by Cropi** [comment]
Hi @monolidth 

I am sorry for the late reply. Judging from the Trace that you provided, the only problem I can think about is that you used ```sudo``` to execute usbguard-notifier. In case you do that, the notifier will not know where it should send the notification.
Could you try it without it?

> Hey Cropi,
> 
> I'm using the latest usbguard and usbguard-notifier version. I installed all required packages mentioned in the **README.md**.
> 
> I did following steps:
> 
>     * ` ./autogen.sh`
> 
>     * ` ./configure --prefix /home/$(id -un)`
> 
>     * `make`
> 
>     * `make install SYSTEMD_UNIT_DIR=/home/$(id -un)/.config/systemd/user/`
> 
>     * `systemctl enable --now --user usbguard-notifier.service`
> 
> 
> ### Trace
> 
> ```
> Connection has been established
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  Failed to show notification
> [2]    40050 abort      sudo ./usbguard-notifier
> ```


> 
> If I run this using the debug flag. I receive this message
> 
> ```
> LOG: src/Notifier.cpp::102 [DevicePresenceChanged] Device presence changed signal
> Connection has been established
> ```
> 
> I hope I could resolve this issue. Thanks for your help.
> 
> Regards,
> William
