### ISSUE TITLE
[RFE] Reduce amount of notifications, make notifications go away

### ISSUE THREAD

**Issue by genodeftest** [Cropi/usbguard-notifier#65]
# Steps to reproduce:
1. have usbguard-notifier running
2. have usbguard configured in a "default deny" policy
3. attach an USB device
4. allow USB device (`usbguard allow-device [number]`)

# What happens:
After 3., I have 2 notifications:
![Bildschirmfoto von 2021-06-04 14-04-54](https://user-images.githubusercontent.com/934401/120798883-4ae38100-c53e-11eb-9438-9f2eabbacd17.png)

After 4., I have 3 notifications:
![Bildschirmfoto von 2021-06-04 14-05-20](https://user-images.githubusercontent.com/934401/120798881-4a4aea80-c53e-11eb-9b9a-e423fca920b3.png)

# What should happen:
Less notifications, max 1 notification per device. As the previous state is not valid any more, it is not of interest.
Possible ideas include:
* Only show one notification per USB device by keeping a reference to the notification of the device until it is dismissed. Every time the device changes its state, update the notification (using `Notify.Notification.update()`) instead of creating a new notification.
* Dismiss notifications after some time.

# Installed software versions:
usbguard-1.0.0-4.fc34.x86_64
usbguard-notifier-0.0.6-4.fc34.x86_64
glib2-2.68.2-1.fc34.x86_64
libnotify-0.7.9-4.fc34.x86_64

**EDIT:**
Note: My USB device seems to have an empty name, which is also being reported as empty by `usbguard list-devices` in the `name` field.

**Comment by Cropi** [comment]
Hi @genodeftest,

Thanks for your cooperation. We had a really similar issue, see https://github.com/Cropi/usbguard-notifier/pull/61 . We do merge notifications when inserting new devices. It's already implemented on upstream but not yet backported to the distribution you are using, I guess it's **Fedora 34**.

**Comment by genodeftest** [comment]
Hi Cropi,
thanks for already implementing this!
And yes, I'm using Fedora 34.

Are you planning on doing a newer release with #61 included?

**Comment by Cropi** [comment]
It's enough to backport the appropriate patch to Fedora. I've created a bugzilla for this, let's continue it under https://bugzilla.redhat.com/show_bug.cgi?id=1972505 as it is not an upstream issue.
