### ISSUE TITLE
How to install it on Ubuntu 20.04?

### ISSUE THREAD

**Issue by MatejKovacic** [Cropi/usbguard-notifier#66]
I am trying to install `usbguard-notifier` on Ubuntu 20.04 and I did the following:
```
git clone https://github.com/Cropi/usbguard-notifier
cd usbguard-notifier/
./autogen.sh
```

Then I run:
`./configure --prefix /home/$(id -un)`

...and get the error:
```
checking for unistd.h... (cached) yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for usbguard... no
configure: error: in `/home/matej/usbguard-notifier':
configure: error: libusbguard development files not found
See `config.log' for more details
```

`usbguard` is running (I can see it is active by running `sudo service usbguard status`, any other idea what could be wrong?

In config.log file I can see things like this (but I do not know if that is relevant):
```
...
configure:3544: g++ -V >&5
g++: error: unrecognized command line option '-V'
g++: fatal error: no input files
compilation terminated.
configure:3555: $? = 1
configure:3544: g++ -qversion >&5
g++: error: unrecognized command line option '-qversion'; did you mean '--version'?
g++: fatal error: no input files
compilation terminated.
...
configure:8548: gcc -E  conftest.c
conftest.c:11:10: fatal error: ac_nonexistent.h: No such file or directory
   11 | #include <ac_nonexistent.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
...
conftest.c:62:53: warning: integer overflow in expression of type 'int' results in '-2147483648' [-Woverflow]
   62 |    < (int32_t) (((((int32_t) 1 << N) << N) - 1) * 2 + 2))];
      |                                                     ^
conftest.c:61:12: error: storage size of 'test_array' isn't constant
   61 | static int test_array [1 - 2 * !((int32_t) (((((int32_t) 1 << N) << N) - 1) * 2 + 1)
      |            ^~~~~~~~~~
configure:12179: $? = 1
```

**Comment by Thulium-Drake** [comment]
Worth noting that the Debian distribution of USBguard does not contain the usual '-dev' package:

```bash
$ apt search usbguard
Sorting... Done
Full Text Search... Done
libusbguard0/stable,now 1.0.0+ds-2 amd64 [installed,automatic]
  USB device authorization policy framework - shared library

usbguard/stable,now 1.0.0+ds-2 amd64 [installed]
  USB device authorization policy framework
$
```
So the question more is, where can we Debian users find them? :-)

**Comment by Cropi** [comment]
It bothers me that there is no such package as ```usbguard-dev``` on Ubuntu. The best place to solve this would be to request it from the official usbguard maintainer on ubuntu.

Anyway, let's say that you compiled usbguard from sources and cloned usbguard-notifier. You can pass additional parameter ```--with-usbguard-devel="/path/to/usbguard-folder"``` to ```configure```.  Let me know if that helps.

**Comment by Thulium-Drake** [comment]
Been a while since I had the time to have a look at it. Which files are you actually looking for? I now have a directory with the result of ```make install``` from usbguard. It contains some files in ```/opt/usbguard/include/usbguard```  (I installed it in the ```/opt/usbguard``` prefix). 

And it still complains :)

**Comment by Thulium-Drake** [comment]
Got it! You need to have the compiled source directory ready, thanks for the hint! I can now proceed ;-)

**Comment by Thulium-Drake** [comment]
Rather important note, this requires the ```master``` branch, the tagged version ```0.0.6``` does _not_ support the ```--with-usbguard-devel=/blah``` option.. Took me some time to figure that one out :/

**Comment by Cropi** [comment]
Even though the development files are not present in the ubuntu repositories, there is a workaround for that by compiling the sources. Closing this as done.
